### ISSUE TITLE
Strange flashing

### ISSUE THREAD

**Issue by mczero80** [ChuckyGang/DiagROM#1]
Hey, I know this might be not the right place to ask.
But in my case, the DiagRom is first showing some color bars, then it flashes red/black (there is nothing about red/black in the the txt file when I download diagrom!), then there are wild colors all over the screen and then just white or light gray.

Might you take a look?
https://www.youtube.com/watch?v=O5KMuofvKXw

Thank you very much!

**Comment by tomten** [comment]
Closed why?

**Comment by mczero80** [comment]
Hello,

I am sorry, it was a whole different Rom that I got from a friend. I thought it was DiagRom but it was Logica Diagnostic.
________________________________
