### ISSUE TITLE
NTSC system and display issues

### ISSUE THREAD

**Issue by Sinphaltimus** [ChuckyGang/DiagROM#2]
I have an NTSC Amiga using an A520 to output composite video to NTSC TV. My NTSC setup is behaving as if the video signal is in PAL mode. I suspect DiagRom video output to be PAL and therefore cannot view output via NTSC video display. I've tried this on 2 different LCD displays and one CRT.

See public facebook video for demonstration of the issue - no FB account needed - https://www.facebook.com/SExmortus/v...84179994209792

**Comment by ChuckyGang** [comment]
Yes it sets to PAL at startup, in next version I will add a possability to press space while being in the mainmeny to switch between screenmodes. (it is actually alreadydone)
