### ISSUE TITLE
Not an issue, just a question

### ISSUE THREAD

**Issue by lazaj** [ChuckyGang/DiagROM#20]
First of all thanks for your job.

Let me introduce myself.
I am a senior electronic and embedded software engineer.
I have been restoring amigas, 68k Mac & 8/16 bits computers for a long time.
I recently lost my job, I am now freelancing.
I created a Tindie shop to sell my products but also to offer retro electronic products at low prices (not everyone can order PCBs online and solder the components).
I have lots of eproms.
I would like to sell the diagroms on 1 eprom 8€ and on 2 eprom 16€.
I will make a donation of 1€ per order.
Do you agree ?

**Comment by QuillOmega0** [comment]
You should read the file called LICENSE.
That should answer any and all your questions

**Comment by lazaj** [comment]
Thanks the LICENSE is pretty clear.
